// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
// Load .env before `env()` / Prisma read the datasource URL (CLI may not inject .env into this module yet).
import "dotenv/config"; //it help with reading the private keys in your .env file
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
